### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by nvivo** [arnoldasgudas/Hangfire.MySqlStorage#26]
Everytime I start hangfire, I get this error on the log:

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at Hangfire.MySql.MySqlStorage.ToString()
```

Things seem to work, but I guess this shouldn't happen.

**Comment by kasimkiller** [comment]
I got the same problem, the file can not be open T^T

**Comment by eassaHolo** [comment]
same thing with me . that is how i added hangfire: 
 ```

 services.AddHangfire(configuration => {
                configuration.UseStorage(
                    new MySqlStorage(Configuration.GetConnectionString("DefaultConnection")));
            });
```
